# Generated by Django 5.1.2 on 2026-05-16 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("fecha_inicio", models.DateField()),
                ("empresa_organizacion", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("objetivos", models.TextField()),
                (
                    "imagen_1",
                    models.ImageField(blank=True, null=True, upload_to="proyectos/"),
                ),
                (
                    "imagen_2",
                    models.ImageField(blank=True, null=True, upload_to="proyectos/"),
                ),
                (
                    "imagen_3",
                    models.ImageField(blank=True, null=True, upload_to="proyectos/"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "docente_lider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos_liderados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegranteProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("docente", "Docente"),
                            ("estudiante", "Estudiante"),
                            ("externo", "Externo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrantes",
                        to="ProyectosApp.proyecto",
                    ),
                ),
            ],
        ),
    ]
