# Generated by Django 5.1.2 on 2026-05-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProyectosApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="trl",
            field=models.CharField(
                choices=[
                    ("TRL1", "TRL 1"),
                    ("TRL2", "TRL 2"),
                    ("TRL3", "TRL 3"),
                    ("TRL4", "TRL 4"),
                    ("TRL5", "TRL 5"),
                    ("TRL6", "TRL 6"),
                    ("TRL7", "TRL 7"),
                    ("TRL8", "TRL 8"),
                ],
                default="TRL1",
                max_length=10,
            ),
        ),
    ]
