# Generated by Django 5.1.2 on 2026-05-17 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProyectosApp", "0002_proyecto_trl"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="modificado",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_modificados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
