# Generated by Django 5.1.2 on 2026-05-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProyectosApp", "0003_proyecto_creado_por_proyecto_modificado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="lugar",
            field=models.CharField(default="Inacap", max_length=200),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="descripcion",
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="objetivos",
            field=models.TextField(max_length=300),
        ),
    ]
