# Generated by Django 5.1.2 on 2026-05-19 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ProyectosApp", "0004_proyecto_lugar_alter_proyecto_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="integranteproyecto",
            options={"ordering": ["rol", "nombre"]},
        ),
    ]
