# Generated by Django 5.1.2 on 2026-05-19 01:37

from django.db import migrations, models

import ProyectosApp.models


class Migration(migrations.Migration):
    dependencies = [
        ("ProyectosApp", "0005_alter_integranteproyecto_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="imagen_1",
            field=models.ImageField(
                blank=True, null=True, upload_to=ProyectosApp.models.proyecto_image_path
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="imagen_2",
            field=models.ImageField(
                blank=True, null=True, upload_to=ProyectosApp.models.proyecto_image_path
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="imagen_3",
            field=models.ImageField(
                blank=True, null=True, upload_to=ProyectosApp.models.proyecto_image_path
            ),
        ),
    ]
