# Generated by Django 5.1.2 on 2026-05-27 00:06

import django.db.models.deletion
from django.db import migrations, models

import ProyectosApp.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ProyectosApp",
            "0006_alter_proyecto_imagen_1_alter_proyecto_imagen_2_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecursoProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("imagen", "Imagen"),
                            ("video", "Video"),
                            ("enlace", "Enlace externo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ProyectosApp.models.recurso_proyecto_path,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recursos",
                        to="ProyectosApp.proyecto",
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "titulo"],
            },
        ),
    ]
