# Generated by Django 5.1.2 on 2026-05-27 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ProyectosApp", "0007_recursoproyecto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recursoproyecto",
            options={"ordering": ["titulo"]},
        ),
        migrations.RemoveField(
            model_name="recursoproyecto",
            name="tipo",
        ),
    ]
