# Generated by Django 5.1.2 on 2026-09-20 01:35

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import DendometroApp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dendrometro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación / árbol"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, verbose_name="Habilitado para sincronizar"
                    ),
                ),
                (
                    "channel_id",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Channel ID",
                    ),
                ),
                (
                    "field_id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="Campo de señal",
                    ),
                ),
                (
                    "state_field_id",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="Campo de estado",
                    ),
                ),
                (
                    "read_api_key",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Read API Key"
                    ),
                ),
                (
                    "configuracion",
                    models.JSONField(default=DendometroApp.models.default_config),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("sincronizado_desde", models.DateTimeField(blank=True, null=True)),
                ("ultima_sincronizacion", models.DateTimeField(blank=True, null=True)),
                ("ultimo_error", models.CharField(blank=True, max_length=250)),
                ("creado", models.DateTimeField(default=django.utils.timezone.now)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dendrómetro",
                "verbose_name_plural": "Dendrómetros",
                "ordering": ["nombre", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Lectura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("entry_id", models.BigIntegerField(null=True)),
                ("value", models.FloatField()),
                ("estado", models.FloatField(null=True)),
                (
                    "dendrometro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturas",
                        to="DendometroApp.dendrometro",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["dendrometro", "created_at"], name="dendro_sensor_fecha"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dendrometro", "created_at"),
                        name="dendro_lectura_unica",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Sincronizacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("estado", models.CharField(default="pendiente", max_length=12)),
                ("rangos", models.JSONField(default=list)),
                ("inicio", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                ("segundos_completos", models.FloatField(default=0)),
                ("registros", models.PositiveIntegerField(default=0)),
                ("omitidos", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=250)),
                ("lease_until", models.DateTimeField(null=True)),
                ("lease_token", models.UUIDField(null=True)),
                (
                    "actualizado",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "dendrometro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sincronizaciones",
                        to="DendometroApp.dendrometro",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "pendiente")),
                        fields=("dendrometro",),
                        name="dendro_sync_activa_unica",
                    )
                ],
            },
        ),
    ]
